
// import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/component/theme/theme-provider";
import QueryProvider from "@/component/QueryProvider";
import { Toaster } from 'react-hot-toast';
import { RouteLoader } from '@/component/RouteLoader';
import Script from "next/script";

import { UserProvider } from "@/context/UserContext";
// export const metadata: Metadata = {
//   title: "صفحه اصلی",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="fa"
      dir="rtl"
      suppressHydrationWarning
    >
      <body
        className={`font-main antialiased h-full
        transition-colors duration-500 text-black dark:bg-zinc-900 dark:text-white
        `}
      >
        {/* این اسکریپت جلوی فلیکر تم رنگی رو می‌گیره */}
        <Script id="init-color-theme" strategy="beforeInteractive">
          {`try {
              const t = localStorage.getItem('color-theme') || 'rose';
              document.documentElement.setAttribute('data-theme', t);
            } catch(e) {}`}
        </Script>
        <RouteLoader />
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {/* <ThemeSwitcher /> */}
          <QueryProvider>
            <div className="relative mx-auto max-h-screen overflow-x-hidden bg-white">
              <UserProvider>


                {children}

              </UserProvider>

            </div>
            <Toaster position="top-right" />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
