
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/component/theme/theme-provider";
// import ThemeSwitcher from "@/component/theme/ThemeSwitcher";
import localFont from "next/font/local";
import QueryProvider from "@/component/QueryProvider";
import { Toaster } from 'react-hot-toast';
import { auth } from "@/lib/auth";
import { SessionProvider } from "next-auth/react";
import { RouteLoader } from '@/component/RouteLoader';
import Script from "next/script";

// import PageTransition from '@/component/PageTransition'
const yekanBakh = localFont({
  src: [
    {
      path: "../../public/fonts/yekanBakh/Yekan-Bakh-FaNum-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekanBakh/Yekan-Bakh-FaNum-Medium.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekanBakh/Yekan-Bakh-FaNum-Bold.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-my-local",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${yekanBakh.variable} font-main`}
      suppressHydrationWarning
    >
      <body
        className={`font-main antialiased h-full
        transition-colors duration-500 text-black dark:bg-zinc-900 dark:text-white
        `}
      >
              {/* این اسکریپت جلوی فلیکر تم رنگی رو می‌گیره */}
        <Script id="init-color-theme" strategy="beforeInteractive">
          {`try {
              const t = localStorage.getItem('color-theme') || 'rose';
              document.documentElement.setAttribute('data-theme', t);
            } catch(e) {}`}
        </Script>
          <RouteLoader />
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {/* <ThemeSwitcher /> */}
          <QueryProvider>
            <div className="relative mx-auto max-h-screen overflow-x-hidden bg-white">
              <SessionProvider session={session}>  
             
                    {children}
             
              </SessionProvider>
            </div>
            <Toaster position="top-right" />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
